kind: pipeline
name: default

steps:
- name: unit-test
  image: golang:1.12
  commands:
  # Unit tests, coverage and race condition checker
  - go test -race -cover -covermode=atomic -coverprofile=coverage.out ./...

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
    - coverage.out

- name: docker
  image: plugins/docker
  settings:
    repo: nsmith5/vgraas
    autotag: true
    force_tag: true
    username: nsmith5
    password:
      from_secret: docker_password

- name: deploy-staging
  image: quay.io/ipedrazas/drone-helm
  settings:
    chart: ./chart
    release: staging
    values: namespace=staging,image.tag=latest
    api_server:
      from_secret: api_server
    kubernetes_token:
      from_secret: kubernetes_token

- name: deploy-production
  image: quay.io/ipedrazas/drone-helm
  settings:
    chart: ./chart
    release: production
    values: namespace=production,image.tag=${TAG}
    api_server:
      from_secret: api_server
    kubernetes_token:
      from_secret: kubernetes_token
