kind: pipeline
name: default

steps:
- name: unit-test
  image: golang:1.12
  commands:
  # Unit tests, coverage and race condition checker
  - go test -race -cover -covermode=atomic -coverprofile=coverage.out ./...

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
    - coverage.out

- name: docker
  image: plugins/docker
  settings:
    repo: nsmith5/vgraas
    autotag: true
    force_tag: true
    username: nsmith5
    password:
      from_secret: docker_password

- name: helm-template
  image: lachlanevenson/k8s-helm
  commands:
  - "helm template chart --name staging --set namespace=staging > deploy.yaml"
   
- name: deploy-staging
  image: bitnami/kubectl:1.14
  environment:
    CONFIG:
      from_secret: kubeconfig
  commands:
  - mkdir -p ~/.kube/config
  - "echo $$CONFIG > ~/.kube/config"
  - kubectl get pods
  - kubectl apply -f deploy.yaml
