openapi: 3.0.1
info:
  title: vgraas
  description: 'This is a simple video game review API'
  contact:
    email: vgraas@nfsmith.ca
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 0.1.1
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/nsmith5/vrgaas/0.1.1
- url: https://vgraas.nfsmith.ca
tags:
- name: reviews
  description: Video game reviews
- name: comments
  description: Video game review comments
paths:
  /reviews/:
    get:
      tags:
      - reviews
      summary: Get all reviews
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - reviews
      summary: Post a new review
      operationId: CreateReview
      requestBody:
        description: Review to post
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        200:
          description: Successfully created a review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ID'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /reviews/{id}:
    get:
      tags:
      - reviews
      summary: Find review by ID
      description: Returns a single review
      parameters:
      - name: id
        in: path
        description: ID of review to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - reviews
      summary: Updates a review
      parameters:
      - name: id
        in: path
        description: ID of review that needs to be updated
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        200:
          description: Success
          content: {}
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - reviews
      summary: Deletes a revjiew
      parameters:
      - name: id
        in: path
        description: Review id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /reviews/{id}/comments:
    get:
      tags:
      - comments
      summary: Read all comments on a review
      parameters:
      - name: id
        in: path
        description: ID of review with comments
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - comments
      summary: Create a new comment on a review
      parameters:
      - name: id
        in: path
        description: ID of review with comments
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /reviews/{id}/comments/{cid}:
    get:
      tags:
      - comments
      summary: Read one comment
      parameters:
      - name: id
        in: path
        description: ID of review
        required: true
        schema:
          type: integer
          format: int64
      - name: cid
        in: path
        description: ID of comment
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - comments
      summary: Update one comment
      parameters:
      - name: id
        in: path
        description: ID of review
        required: true
        schema:
          type: integer
          format: int64
      - name: cid
        in: path
        description: ID of comment
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: successful operation
          content: {}
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - comments
      summary: delete one comment
      parameters:
      - name: id
        in: path
        description: ID of review
        required: true
        schema:
          type: integer
          format: int64
      - name: cid
        in: path
        description: ID of comment
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content: {}
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        400:
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Review:
      type: object
      properties:
        author:
          type: string
        body:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Comment:
      type: object
      properties:
        author:
          type: string
        body:
          type: string
    Error:
      type: object
      properties:
        err:
          type: string
    ID:
      type: object
      properties:
        id:
          type: integer
          format: int32