apiVersion: v1
kind: Service
metadata:
  name: vgraas
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vgraas
    app.kubernetes.io/instance: {{ .Release.Name }}
